kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: docker
  image: plugins/docker
  settings:
    dockerfile: ./10.3/debian-9/Dockerfile
    context: ./10.3/debian-9/
    username: justinbarrick
    password:
      from_secret: docker_password
    repo: justinbarrick/external-dns
    tags: latest
